apiVersion: v1
kind: Service
metadata:
  name: {{ include "ovaldgehelmchart.fullname" . }}
  namespace: ingress-nginx
  labels:
    {{- include "ovaldgehelmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "ovaldgehelmchart.selectorLabels" . | nindent 4 }}
